[package]
name = "sodium"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "na"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
walkdir = "2"
atty = "0.2"
lscolors = "0.9"
ansi_term = "0.12"
terminal_size = "0.1"
term_grid = "0.2"
